apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: gcr.io/lbg-mea-16/steve-project-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080